-- =====================================================
-- Clinical Trial Data Management - Table Creation Script
-- Creates core tables for clinical trial data capture
-- Run this script in Oracle SQL Developer
-- =====================================================

-- Drop tables if they exist (for clean setup)
-- Uncomment if you need to recreate tables
/*
DROP TABLE lab_result CASCADE CONSTRAINTS;
DROP TABLE visit CASCADE CONSTRAINTS;
DROP TABLE subject CASCADE CONSTRAINTS;
DROP TABLE site CASCADE CONSTRAINTS;
DROP TABLE study CASCADE CONSTRAINTS;
*/

-- =====================================================
-- STUDY Table
-- Represents a clinical trial study
-- =====================================================
CREATE TABLE study (
    study_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_name VARCHAR2(200) NOT NULL,
    study_number VARCHAR2(50) UNIQUE NOT NULL,
    protocol_number VARCHAR2(100),
    study_status VARCHAR2(50) DEFAULT 'ACTIVE',
    start_date DATE,
    end_date DATE,
    description VARCHAR2(1000),
    created_date DATE DEFAULT SYSDATE,
    created_by VARCHAR2(100) DEFAULT USER
);

-- =====================================================
-- SITE Table
-- Represents clinical trial sites/investigational sites
-- =====================================================
CREATE TABLE site (
    site_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id NUMBER NOT NULL,
    site_number VARCHAR2(50) NOT NULL,
    site_name VARCHAR2(200) NOT NULL,
    site_address VARCHAR2(500),
    site_city VARCHAR2(100),
    site_state VARCHAR2(50),
    site_country VARCHAR2(100),
    principal_investigator VARCHAR2(200),
    site_status VARCHAR2(50) DEFAULT 'ACTIVE',
    created_date DATE DEFAULT SYSDATE,
    created_by VARCHAR2(100) DEFAULT USER,
    CONSTRAINT fk_site_study FOREIGN KEY (study_id) REFERENCES study(study_id),
    CONSTRAINT uk_site_study_number UNIQUE (study_id, site_number)
);

-- =====================================================
-- SUBJECT Table
-- Represents trial participants/subjects
-- =====================================================
CREATE TABLE subject (
    subject_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id NUMBER NOT NULL,
    site_id NUMBER NOT NULL,
    subject_number VARCHAR2(50) NOT NULL,
    screening_number VARCHAR2(50),
    randomization_number VARCHAR2(50),
    date_of_birth DATE,
    gender VARCHAR2(20),
    enrollment_date DATE,
    status VARCHAR2(50) DEFAULT 'ENROLLED',
    created_date DATE DEFAULT SYSDATE,
    created_by VARCHAR2(100) DEFAULT USER,
    CONSTRAINT fk_subject_study FOREIGN KEY (study_id) REFERENCES study(study_id),
    CONSTRAINT fk_subject_site FOREIGN KEY (site_id) REFERENCES site(site_id),
    CONSTRAINT uk_subject_study_number UNIQUE (study_id, site_id, subject_number)
);

-- =====================================================
-- VISIT Table
-- Represents subject visits during the trial
-- =====================================================
CREATE TABLE visit (
    visit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id NUMBER NOT NULL,
    visit_number NUMBER NOT NULL,
    visit_name VARCHAR2(100),
    visit_date DATE,
    visit_status VARCHAR2(50) DEFAULT 'SCHEDULED',
    visit_window_start DATE,
    visit_window_end DATE,
    created_date DATE DEFAULT SYSDATE,
    created_by VARCHAR2(100) DEFAULT USER,
    CONSTRAINT fk_visit_subject FOREIGN KEY (subject_id) REFERENCES subject(subject_id),
    CONSTRAINT uk_visit_subject_number UNIQUE (subject_id, visit_number)
);

-- =====================================================
-- LAB_RESULT Table
-- Represents laboratory test results
-- =====================================================
CREATE TABLE lab_result (
    lab_result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id NUMBER NOT NULL,
    test_name VARCHAR2(200) NOT NULL,
    test_code VARCHAR2(50),
    test_value NUMBER(18,4),
    test_unit VARCHAR2(50),
    normal_range_low NUMBER(18,4),
    normal_range_high NUMBER(18,4),
    result_status VARCHAR2(50) DEFAULT 'NORMAL',
    collection_date DATE,
    result_date DATE,
    created_date DATE DEFAULT SYSDATE,
    created_by VARCHAR2(100) DEFAULT USER,
    CONSTRAINT fk_lab_visit FOREIGN KEY (visit_id) REFERENCES visit(visit_id)
);

-- =====================================================
-- Create Indexes for Performance
-- =====================================================
CREATE INDEX idx_site_study_id ON site(study_id);
CREATE INDEX idx_subject_study_id ON subject(study_id);
CREATE INDEX idx_subject_site_id ON subject(site_id);
CREATE INDEX idx_visit_subject_id ON visit(subject_id);
CREATE INDEX idx_lab_visit_id ON lab_result(visit_id);
CREATE INDEX idx_lab_test_name ON lab_result(test_name);
CREATE INDEX idx_lab_result_status ON lab_result(result_status);

-- =====================================================
-- Add Comments for Documentation
-- =====================================================
COMMENT ON TABLE study IS 'Clinical trial studies';
COMMENT ON TABLE site IS 'Investigational sites participating in studies';
COMMENT ON TABLE subject IS 'Trial participants/subjects';
COMMENT ON TABLE visit IS 'Subject visits during the trial';
COMMENT ON TABLE lab_result IS 'Laboratory test results for visits';

COMMENT ON COLUMN study.study_status IS 'ACTIVE, COMPLETED, TERMINATED, etc.';
COMMENT ON COLUMN site.site_status IS 'ACTIVE, INACTIVE, CLOSED, etc.';
COMMENT ON COLUMN subject.status IS 'ENROLLED, SCREENED, RANDOMIZED, COMPLETED, DISCONTINUED, etc.';
COMMENT ON COLUMN visit.visit_status IS 'SCHEDULED, COMPLETED, MISSED, CANCELLED, etc.';
COMMENT ON COLUMN lab_result.result_status IS 'NORMAL, ABNORMAL, OUT_OF_RANGE, etc.';

PROMPT =====================================================
PROMPT Tables created successfully!
PROMPT =====================================================
PROMPT Created tables:
PROMPT   - STUDY
PROMPT   - SITE
PROMPT   - SUBJECT
PROMPT   - VISIT
PROMPT   - LAB_RESULT
PROMPT =====================================================
